server:
  port: 9527
spring:
  application:
    name: servicecloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /ltyl
#  ignored-services: "*"
  routes:
    mydept.serviceId: servicecloud-dept
    mydept.path: /mydept/**
  ignored-services: servicecloud-dept




info:
  app.name: ltyl-servicecloud
  company.name: www.ltyl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$





