server:
  port: 3344


spring:
  application:
    name: servicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lihongru-bt/servicecloud-config.git  #GitHub上的git仓库名字

