server:
  port: 8002


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis配置文件所在的路径
  type-aliases-package: com.ltyl.entities                #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml    #mapper映射文件

spring:
  application:
    name: servicecloud-dept
  datasource:
   # type: com.alibaba.druid.pool.DruidDataSource     #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver       #mysql的驱动包
    url: jdbc:mysql://106.52.28.89:13306/cloudDB02    #数据库名称
    username: root
    password: Password01!
    dbcp2:
      min-idle: 5                                   #数据库连接池的最小维持连接数
      initial-size: 5                               #初始化连接数
      max-total: 5                                  #最大连接数
      max-wait-millis: 200                          #等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      # 单机 defaultZone: http://127.0.0.1:7001/eureka
  register-with-eureka: true   #false 表示不向注册中心注册自己
  fetch-registry: true     #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
  instance:
    instance-id: servicecloud-dept8002   #主机名称：服务名称的修改  自定义服务信息
    prefer-ip-address: true  #访问路径可以显示IP地址


info:
  app.name: ltyl-servicecloud
  company.name: www.ltyl.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

